-- Starter content. Run once, after 0001_init.sql. Re-running is harmless (unique text).

insert into public.question_bank (text, category) values
  ('What is a small thing I do that you secretly love?', 'us'),
  ('What was the best part of your day?', 'daily'),
  ('If we could teleport for one evening, where should we have dinner?', 'dreams'),
  ('What song reminds you of us right now?', 'us'),
  ('What is something you are looking forward to this month?', 'daily'),
  ('When did you first realise you liked me?', 'us'),
  ('What is one thing you want us to do together this year?', 'dreams'),
  ('What is the funniest thing that happened to you this week?', 'daily'),
  ('Which of my habits makes you smile?', 'us'),
  ('What would your perfect lazy Sunday with me look like?', 'dreams'),
  ('What is a memory of us you replay in your head?', 'us'),
  ('What is something you are proud of lately?', 'daily'),
  ('What is one thing that stressed you out this week, and how can I help?', 'daily'),
  ('Which city should we visit together first, and why?', 'dreams'),
  ('What is your comfort food when you miss me?', 'us'),
  ('What is something you learned about yourself recently?', 'daily'),
  ('If I could cook you one meal, what should it be?', 'dreams'),
  ('What is the first thing you want to do when we meet next?', 'us'),
  ('What was your favourite thing about your childhood?', 'deep'),
  ('What is a fear you would like to get over?', 'deep'),
  ('What does home feel like to you?', 'deep'),
  ('Which movie should we watch together next?', 'fun'),
  ('If we had a pet together, what would we name it?', 'fun'),
  ('What is the most spontaneous thing you have ever done?', 'fun'),
  ('What is one thing you wish I knew about your day-to-day?', 'deep'),
  ('What is the sweetest thing someone has done for you?', 'deep'),
  ('What would you put in a time capsule for us?', 'dreams'),
  ('What is a tiny ritual you want us to have?', 'us'),
  ('What do you think we will be doing in five years?', 'dreams'),
  ('What is one word to describe how you feel right now?', 'daily')
on conflict (text) do nothing;

insert into public.prompts (option_a, option_b, category) values
  ('Beach holiday', 'Mountain cabin', 'travel'),
  ('Cook together', 'Order in', 'food'),
  ('Movie night', 'Game night', 'evening'),
  ('Sunrise', 'Sunset', 'vibes'),
  ('Cats', 'Dogs', 'animals'),
  ('Tea', 'Coffee', 'food'),
  ('Rain', 'Snow', 'weather'),
  ('Text all day', 'One long call', 'us'),
  ('Surprise gift', 'Planned date', 'us'),
  ('Sweet', 'Salty', 'food'),
  ('City break', 'Countryside escape', 'travel'),
  ('Early bird', 'Night owl', 'vibes'),
  ('Road trip', 'Train journey', 'travel'),
  ('Handwritten letter', 'Voice note', 'us'),
  ('Pizza', 'Pasta', 'food'),
  ('Dance in the kitchen', 'Stargaze on a roof', 'us'),
  ('Live in London', 'Live in Pune', 'us'),
  ('Summer', 'Winter', 'weather'),
  ('Read together', 'Walk together', 'evening'),
  ('Dessert first', 'Dessert last', 'food'),
  ('Spend a fortune on one trip', 'Lots of small trips', 'travel'),
  ('Matching pyjamas', 'Matching sweaters', 'fun'),
  ('Meet in the middle', 'Take turns visiting', 'us'),
  ('Pancakes', 'Waffles', 'food'),
  ('Sing badly together', 'Dance badly together', 'fun')
on conflict (option_a, option_b) do nothing;
